import { makeFakeGuitars, makeFakeGuitar } from './../../utils/mock';
import { guitarsData } from './guitars-data';
import { loadGuitars, loadGuitarById, setTotalCountGuitarsFromResponse, setIsNewCommentPush } from './guitars-data';
import { Guitar } from '../../types/guitars';

const guitar = makeFakeGuitar();

describe('Reducer: guitarsData', () => {
  it('without additional parameters should return initial state', () => {
    expect(guitarsData.reducer(void 0, {type: 'UNKNOWN_ACTION'}))
      .toEqual({guitarsTotalCount: 0,
        guitars: [],
        guitarsMinPrice: 0,
        guitarsMaxPrice: 0,
        guitarById: {} as Guitar,
        guitarComments: [],
        isGuitarsLoaded: true,
        isGuitarLoaded: true,
        isCommentPushed: false,
        isGuitarsSortFilterLoaded: true,
        search: '',
        searchResults: [],
        sortType: '',
        sortDirection: '',
        filterMinPrice: 0,
        filterMaxPrice: 0,
        filterGuitarTypes: [],
        filterStringCount: []});
  });

  it('should download guitars', () => {
    expect(guitarsData.reducer({guitarsTotalCount: 0,
      guitars: [],
      guitarsMinPrice: 0,
      guitarsMaxPrice: 0,
      guitarById: {} as Guitar,
      guitarComments: [],
      isGuitarsLoaded: true,
      isGuitarLoaded: true,
      isCommentPushed: false,
      isGuitarsSortFilterLoaded: true,
      search: '',
      searchResults: [],
      sortType: '',
      sortDirection: '',
      filterMinPrice: 0,
      filterMaxPrice: 0,
      filterGuitarTypes: [],
      filterStringCount: []}, setTotalCountGuitarsFromResponse(20)))
      .toEqual({
        guitarsTotalCount: 20,
        guitars: [],
        guitarsMinPrice: 0,
        guitarsMaxPrice: 0,
        guitarById: {},
        guitarComments: [],
        isGuitarsLoaded: true,
        isGuitarLoaded: true,
        isCommentPushed: false,
        isGuitarsSortFilterLoaded: true,
        search: '',
        searchResults: [],
        sortType: '',
        sortDirection: '',
        filterMinPrice: 0,
        filterMaxPrice: 0,
        filterGuitarTypes: [],
        filterStringCount: [],
      });
  });

  it('should set total count guitars from response', () => {
    expect(guitarsData.reducer({guitarsTotalCount: 0,
      guitars: [],
      guitarsMinPrice: 0,
      guitarsMaxPrice: 0,
      guitarById: {} as Guitar,
      guitarComments: [],
      isGuitarsLoaded: true,
      isGuitarLoaded: true,
      isCommentPushed: false,
      isGuitarsSortFilterLoaded: true,
      search: '',
      searchResults: [],
      sortType: '',
      sortDirection: '',
      filterMinPrice: 0,
      filterMaxPrice: 0,
      filterGuitarTypes: [],
      filterStringCount: []}, loadGuitars(makeFakeGuitars)))
      .toEqual({guitarsTotalCount: 0,
        guitars: makeFakeGuitars,
        guitarsMinPrice: 15000,
        guitarsMaxPrice: 15000,
        guitarById: {},
        guitarComments: [],
        isGuitarsLoaded: true,
        isGuitarLoaded: true,
        isCommentPushed: false,
        isGuitarsSortFilterLoaded: true,
        search: '',
        searchResults: [],
        sortType: '',
        sortDirection: '',
        filterMinPrice: 0,
        filterMaxPrice: 0,
        filterGuitarTypes: [],
        filterStringCount: []});
  });

  it('should update guitar by load guitar', () => {
    expect(guitarsData.reducer({guitarsTotalCount: 0,
      guitars: [],
      guitarsMinPrice: 0,
      guitarsMaxPrice: 0,
      guitarById: {} as Guitar,
      guitarComments: [],
      isGuitarsLoaded: true,
      isGuitarLoaded: true,
      isCommentPushed: false,
      isGuitarsSortFilterLoaded: true,
      search: '',
      searchResults: [],
      sortType: '',
      sortDirection: '',
      filterMinPrice: 0,
      filterMaxPrice: 0,
      filterGuitarTypes: [],
      filterStringCount: []}, loadGuitarById(guitar)))
      .toEqual({guitarsTotalCount: 0,
        guitars: [],
        guitarsMinPrice: 0,
        guitarsMaxPrice: 0,
        guitarById: makeFakeGuitar(),
        guitarComments: [],
        isGuitarsLoaded: true,
        isGuitarLoaded: true,
        isCommentPushed: false,
        isGuitarsSortFilterLoaded: true,
        search: '',
        searchResults: [],
        sortType: '',
        sortDirection: '',
        filterMinPrice: 0,
        filterMaxPrice: 0,
        filterGuitarTypes: [],
        filterStringCount: []});
  });

  it('should set true when new comment push', () => {
    expect(guitarsData.reducer({guitarsTotalCount: 0,
      guitars: [],
      guitarsMinPrice: 0,
      guitarsMaxPrice: 0,
      guitarById: {} as Guitar,
      guitarComments: [],
      isGuitarsLoaded: true,
      isGuitarLoaded: true,
      isCommentPushed: false,
      isGuitarsSortFilterLoaded: true,
      search: '',
      searchResults: [],
      sortType: '',
      sortDirection: '',
      filterMinPrice: 0,
      filterMaxPrice: 0,
      filterGuitarTypes: [],
      filterStringCount: []}, setIsNewCommentPush(true)))
      .toEqual({guitarsTotalCount: 0,
        guitars: [],
        guitarsMinPrice: 0,
        guitarsMaxPrice: 0,
        guitarById: {},
        guitarComments: [],
        isGuitarsLoaded: true,
        isGuitarLoaded: true,
        isCommentPushed: true,
        isGuitarsSortFilterLoaded: true,
        search: '',
        searchResults: [],
        sortType: '',
        sortDirection: '',
        filterMinPrice: 0,
        filterMaxPrice: 0,
        filterGuitarTypes: [],
        filterStringCount: []});
  });
});
